version: '3.8'
services:
  web_hyphenation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php81
    depends_on:
      - db
    volumes:
      #- ./naujas:/var/www/html/
      - ./hyphenation:/var/www/
    ports:
      - 8000:80