version: '3.8'
services:
  web_hyphenation:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php81-h
    volumes:
      #- ./naujas:/var/www/html/
      - ./hyphenation:/var/www/
    ports:
      - 8000:80
  db_hyphenation:
    container_name: mysql8-h
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyphenation
    ports:
      - 6033:3306