version: '3.8'
services:
  http:
    build:
      context: .
      dockerfile: docker/http/Dockerfile
    container_name: web-hyphenation
    volumes:
      #- ./naujas:/var/www/html/
      - ./hyphenation:/var/www/
    ports:
      - 80:80
  mariadb:
    container_name: mariadb-hyphenation
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hyphenation
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/docker-entrypoint-initdb.d